project_id = "xzoiqjsttggtrjlrhcjm"

[functions.confirm-request-ready]
verify_jwt = false

[functions.save-user-whatsapp]
verify_jwt = false

[functions.notify-request-whatsapp]
verify_jwt = false

[functions.daily-admin-welcome-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.admin-whatsapp-reply]
verify_jwt = false
