/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWhatsappUsuariosRouteImport } from './routes/admin.whatsapp-usuarios'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminRequisicaoRouteImport } from './routes/admin.requisicao'
import { Route as AdminMinhasRequisicoesRouteImport } from './routes/admin.minhas-requisicoes'
import { Route as AdminMinhasAssinaturasRouteImport } from './routes/admin.minhas-assinaturas'
import { Route as AdminMeusAssinadosRouteImport } from './routes/admin.meus-assinados'
import { Route as AdminConversasRouteImport } from './routes/admin.conversas'
import { Route as AdminControleEntradasRouteImport } from './routes/admin.controle-entradas'
import { Route as AdminControleAssinaturasRouteImport } from './routes/admin.controle-assinaturas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCompletarCadastroRouteImport } from './routes/admin.completar-cadastro'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAssinadasRouteImport } from './routes/admin.assinadas'
import { Route as AdminCadastrosUsuariosRouteImport } from './routes/admin.cadastros.usuarios'
import { Route as AdminCadastrosProgramasRouteImport } from './routes/admin.cadastros.programas'
import { Route as AdminCadastrosProdutosRouteImport } from './routes/admin.cadastros.produtos'
import { Route as AdminCadastrosLocaisRouteImport } from './routes/admin.cadastros.locais'
import { Route as AdminBackupLocalRouteImport } from './routes/admin.backup.local'
import { Route as AdminSolicitacoesRequisicaoIdPdfRouteImport } from './routes/admin.solicitacoes.$requisicaoId.pdf'
import { Route as AdminMinhasAssinaturasRequisicaoIdPdfRouteImport } from './routes/admin.minhas-assinaturas.$requisicaoId.pdf'
import { Route as AdminMeusAssinadosRequisicaoIdPdfRouteImport } from './routes/admin.meus-assinados.$requisicaoId.pdf'
import { Route as AdminCadastrosUsuariosUsuarioIdRouteImport } from './routes/admin.cadastros.usuarios.$usuarioId'
import { Route as AdminCadastrosProgramasProgramaIdRouteImport } from './routes/admin.cadastros.programas.$programaId'
import { Route as AdminCadastrosProdutosProdutoIdRouteImport } from './routes/admin.cadastros.produtos.$produtoId'
import { Route as AdminCadastrosLocaisLocalIdRouteImport } from './routes/admin.cadastros.locais.$localId'
import { Route as AdminAssinadasRequisicaoIdPdfRouteImport } from './routes/admin.assinadas.$requisicaoId.pdf'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappUsuariosRoute = AdminWhatsappUsuariosRouteImport.update({
  id: '/whatsapp-usuarios',
  path: '/whatsapp-usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequisicaoRoute = AdminRequisicaoRouteImport.update({
  id: '/requisicao',
  path: '/requisicao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinhasRequisicoesRoute = AdminMinhasRequisicoesRouteImport.update({
  id: '/minhas-requisicoes',
  path: '/minhas-requisicoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinhasAssinaturasRoute = AdminMinhasAssinaturasRouteImport.update({
  id: '/minhas-assinaturas',
  path: '/minhas-assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeusAssinadosRoute = AdminMeusAssinadosRouteImport.update({
  id: '/meus-assinados',
  path: '/meus-assinados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversasRoute = AdminConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControleEntradasRoute = AdminControleEntradasRouteImport.update({
  id: '/controle-entradas',
  path: '/controle-entradas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControleAssinaturasRoute =
  AdminControleAssinaturasRouteImport.update({
    id: '/controle-assinaturas',
    path: '/controle-assinaturas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompletarCadastroRoute = AdminCompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinadasRoute = AdminAssinadasRouteImport.update({
  id: '/assinadas',
  path: '/assinadas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosUsuariosRoute = AdminCadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosProgramasRoute = AdminCadastrosProgramasRouteImport.update({
  id: '/cadastros/programas',
  path: '/cadastros/programas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosProdutosRoute = AdminCadastrosProdutosRouteImport.update({
  id: '/cadastros/produtos',
  path: '/cadastros/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosLocaisRoute = AdminCadastrosLocaisRouteImport.update({
  id: '/cadastros/locais',
  path: '/cadastros/locais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupLocalRoute = AdminBackupLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => AdminBackupRoute,
} as any)
const AdminSolicitacoesRequisicaoIdPdfRoute =
  AdminSolicitacoesRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminSolicitacoesRoute,
  } as any)
const AdminMinhasAssinaturasRequisicaoIdPdfRoute =
  AdminMinhasAssinaturasRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminMinhasAssinaturasRoute,
  } as any)
const AdminMeusAssinadosRequisicaoIdPdfRoute =
  AdminMeusAssinadosRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminMeusAssinadosRoute,
  } as any)
const AdminCadastrosUsuariosUsuarioIdRoute =
  AdminCadastrosUsuariosUsuarioIdRouteImport.update({
    id: '/$usuarioId',
    path: '/$usuarioId',
    getParentRoute: () => AdminCadastrosUsuariosRoute,
  } as any)
const AdminCadastrosProgramasProgramaIdRoute =
  AdminCadastrosProgramasProgramaIdRouteImport.update({
    id: '/$programaId',
    path: '/$programaId',
    getParentRoute: () => AdminCadastrosProgramasRoute,
  } as any)
const AdminCadastrosProdutosProdutoIdRoute =
  AdminCadastrosProdutosProdutoIdRouteImport.update({
    id: '/$produtoId',
    path: '/$produtoId',
    getParentRoute: () => AdminCadastrosProdutosRoute,
  } as any)
const AdminCadastrosLocaisLocalIdRoute =
  AdminCadastrosLocaisLocalIdRouteImport.update({
    id: '/$localId',
    path: '/$localId',
    getParentRoute: () => AdminCadastrosLocaisRoute,
  } as any)
const AdminAssinadasRequisicaoIdPdfRoute =
  AdminAssinadasRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminAssinadasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/backup': typeof AdminBackupRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/controle-assinaturas': typeof AdminControleAssinaturasRoute
  '/admin/controle-entradas': typeof AdminControleEntradasRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/minhas-requisicoes': typeof AdminMinhasRequisicoesRoute
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin/whatsapp-usuarios': typeof AdminWhatsappUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/backup/local': typeof AdminBackupLocalRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRouteWithChildren
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRouteWithChildren
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/locais/$localId': typeof AdminCadastrosLocaisLocalIdRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/programas/$programaId': typeof AdminCadastrosProgramasProgramaIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/backup': typeof AdminBackupRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/controle-assinaturas': typeof AdminControleAssinaturasRoute
  '/admin/controle-entradas': typeof AdminControleEntradasRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/minhas-requisicoes': typeof AdminMinhasRequisicoesRoute
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin/whatsapp-usuarios': typeof AdminWhatsappUsuariosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/backup/local': typeof AdminBackupLocalRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRouteWithChildren
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRouteWithChildren
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/locais/$localId': typeof AdminCadastrosLocaisLocalIdRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/programas/$programaId': typeof AdminCadastrosProgramasProgramaIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/backup': typeof AdminBackupRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/controle-assinaturas': typeof AdminControleAssinaturasRoute
  '/admin/controle-entradas': typeof AdminControleEntradasRoute
  '/admin/conversas': typeof AdminConversasRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/minhas-requisicoes': typeof AdminMinhasRequisicoesRoute
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin/whatsapp-usuarios': typeof AdminWhatsappUsuariosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/backup/local': typeof AdminBackupLocalRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRouteWithChildren
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRouteWithChildren
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/locais/$localId': typeof AdminCadastrosLocaisLocalIdRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/programas/$programaId': typeof AdminCadastrosProgramasProgramaIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/assinadas'
    | '/admin/backup'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/controle-assinaturas'
    | '/admin/controle-entradas'
    | '/admin/conversas'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/minhas-requisicoes'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin/whatsapp-usuarios'
    | '/admin/'
    | '/admin/backup/local'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/locais/$localId'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/programas/$programaId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/assinadas'
    | '/admin/backup'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/controle-assinaturas'
    | '/admin/controle-entradas'
    | '/admin/conversas'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/minhas-requisicoes'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin/whatsapp-usuarios'
    | '/admin'
    | '/admin/backup/local'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/locais/$localId'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/programas/$programaId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/assinadas'
    | '/admin/backup'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/controle-assinaturas'
    | '/admin/controle-entradas'
    | '/admin/conversas'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/minhas-requisicoes'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin/whatsapp-usuarios'
    | '/admin/'
    | '/admin/backup/local'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/locais/$localId'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/programas/$programaId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp-usuarios': {
      id: '/admin/whatsapp-usuarios'
      path: '/whatsapp-usuarios'
      fullPath: '/admin/whatsapp-usuarios'
      preLoaderRoute: typeof AdminWhatsappUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requisicao': {
      id: '/admin/requisicao'
      path: '/requisicao'
      fullPath: '/admin/requisicao'
      preLoaderRoute: typeof AdminRequisicaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minhas-requisicoes': {
      id: '/admin/minhas-requisicoes'
      path: '/minhas-requisicoes'
      fullPath: '/admin/minhas-requisicoes'
      preLoaderRoute: typeof AdminMinhasRequisicoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minhas-assinaturas': {
      id: '/admin/minhas-assinaturas'
      path: '/minhas-assinaturas'
      fullPath: '/admin/minhas-assinaturas'
      preLoaderRoute: typeof AdminMinhasAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meus-assinados': {
      id: '/admin/meus-assinados'
      path: '/meus-assinados'
      fullPath: '/admin/meus-assinados'
      preLoaderRoute: typeof AdminMeusAssinadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversas': {
      id: '/admin/conversas'
      path: '/conversas'
      fullPath: '/admin/conversas'
      preLoaderRoute: typeof AdminConversasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controle-entradas': {
      id: '/admin/controle-entradas'
      path: '/controle-entradas'
      fullPath: '/admin/controle-entradas'
      preLoaderRoute: typeof AdminControleEntradasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controle-assinaturas': {
      id: '/admin/controle-assinaturas'
      path: '/controle-assinaturas'
      fullPath: '/admin/controle-assinaturas'
      preLoaderRoute: typeof AdminControleAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/completar-cadastro': {
      id: '/admin/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/admin/completar-cadastro'
      preLoaderRoute: typeof AdminCompletarCadastroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinadas': {
      id: '/admin/assinadas'
      path: '/assinadas'
      fullPath: '/admin/assinadas'
      preLoaderRoute: typeof AdminAssinadasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/usuarios': {
      id: '/admin/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/admin/cadastros/usuarios'
      preLoaderRoute: typeof AdminCadastrosUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/programas': {
      id: '/admin/cadastros/programas'
      path: '/cadastros/programas'
      fullPath: '/admin/cadastros/programas'
      preLoaderRoute: typeof AdminCadastrosProgramasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/produtos': {
      id: '/admin/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/admin/cadastros/produtos'
      preLoaderRoute: typeof AdminCadastrosProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/locais': {
      id: '/admin/cadastros/locais'
      path: '/cadastros/locais'
      fullPath: '/admin/cadastros/locais'
      preLoaderRoute: typeof AdminCadastrosLocaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup/local': {
      id: '/admin/backup/local'
      path: '/local'
      fullPath: '/admin/backup/local'
      preLoaderRoute: typeof AdminBackupLocalRouteImport
      parentRoute: typeof AdminBackupRoute
    }
    '/admin/solicitacoes/$requisicaoId/pdf': {
      id: '/admin/solicitacoes/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/solicitacoes/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminSolicitacoesRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminSolicitacoesRoute
    }
    '/admin/minhas-assinaturas/$requisicaoId/pdf': {
      id: '/admin/minhas-assinaturas/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/minhas-assinaturas/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminMinhasAssinaturasRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminMinhasAssinaturasRoute
    }
    '/admin/meus-assinados/$requisicaoId/pdf': {
      id: '/admin/meus-assinados/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/meus-assinados/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminMeusAssinadosRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminMeusAssinadosRoute
    }
    '/admin/cadastros/usuarios/$usuarioId': {
      id: '/admin/cadastros/usuarios/$usuarioId'
      path: '/$usuarioId'
      fullPath: '/admin/cadastros/usuarios/$usuarioId'
      preLoaderRoute: typeof AdminCadastrosUsuariosUsuarioIdRouteImport
      parentRoute: typeof AdminCadastrosUsuariosRoute
    }
    '/admin/cadastros/programas/$programaId': {
      id: '/admin/cadastros/programas/$programaId'
      path: '/$programaId'
      fullPath: '/admin/cadastros/programas/$programaId'
      preLoaderRoute: typeof AdminCadastrosProgramasProgramaIdRouteImport
      parentRoute: typeof AdminCadastrosProgramasRoute
    }
    '/admin/cadastros/produtos/$produtoId': {
      id: '/admin/cadastros/produtos/$produtoId'
      path: '/$produtoId'
      fullPath: '/admin/cadastros/produtos/$produtoId'
      preLoaderRoute: typeof AdminCadastrosProdutosProdutoIdRouteImport
      parentRoute: typeof AdminCadastrosProdutosRoute
    }
    '/admin/cadastros/locais/$localId': {
      id: '/admin/cadastros/locais/$localId'
      path: '/$localId'
      fullPath: '/admin/cadastros/locais/$localId'
      preLoaderRoute: typeof AdminCadastrosLocaisLocalIdRouteImport
      parentRoute: typeof AdminCadastrosLocaisRoute
    }
    '/admin/assinadas/$requisicaoId/pdf': {
      id: '/admin/assinadas/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/assinadas/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminAssinadasRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminAssinadasRoute
    }
  }
}

interface AdminAssinadasRouteChildren {
  AdminAssinadasRequisicaoIdPdfRoute: typeof AdminAssinadasRequisicaoIdPdfRoute
}

const AdminAssinadasRouteChildren: AdminAssinadasRouteChildren = {
  AdminAssinadasRequisicaoIdPdfRoute: AdminAssinadasRequisicaoIdPdfRoute,
}

const AdminAssinadasRouteWithChildren = AdminAssinadasRoute._addFileChildren(
  AdminAssinadasRouteChildren,
)

interface AdminBackupRouteChildren {
  AdminBackupLocalRoute: typeof AdminBackupLocalRoute
}

const AdminBackupRouteChildren: AdminBackupRouteChildren = {
  AdminBackupLocalRoute: AdminBackupLocalRoute,
}

const AdminBackupRouteWithChildren = AdminBackupRoute._addFileChildren(
  AdminBackupRouteChildren,
)

interface AdminMeusAssinadosRouteChildren {
  AdminMeusAssinadosRequisicaoIdPdfRoute: typeof AdminMeusAssinadosRequisicaoIdPdfRoute
}

const AdminMeusAssinadosRouteChildren: AdminMeusAssinadosRouteChildren = {
  AdminMeusAssinadosRequisicaoIdPdfRoute:
    AdminMeusAssinadosRequisicaoIdPdfRoute,
}

const AdminMeusAssinadosRouteWithChildren =
  AdminMeusAssinadosRoute._addFileChildren(AdminMeusAssinadosRouteChildren)

interface AdminMinhasAssinaturasRouteChildren {
  AdminMinhasAssinaturasRequisicaoIdPdfRoute: typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
}

const AdminMinhasAssinaturasRouteChildren: AdminMinhasAssinaturasRouteChildren =
  {
    AdminMinhasAssinaturasRequisicaoIdPdfRoute:
      AdminMinhasAssinaturasRequisicaoIdPdfRoute,
  }

const AdminMinhasAssinaturasRouteWithChildren =
  AdminMinhasAssinaturasRoute._addFileChildren(
    AdminMinhasAssinaturasRouteChildren,
  )

interface AdminSolicitacoesRouteChildren {
  AdminSolicitacoesRequisicaoIdPdfRoute: typeof AdminSolicitacoesRequisicaoIdPdfRoute
}

const AdminSolicitacoesRouteChildren: AdminSolicitacoesRouteChildren = {
  AdminSolicitacoesRequisicaoIdPdfRoute: AdminSolicitacoesRequisicaoIdPdfRoute,
}

const AdminSolicitacoesRouteWithChildren =
  AdminSolicitacoesRoute._addFileChildren(AdminSolicitacoesRouteChildren)

interface AdminCadastrosLocaisRouteChildren {
  AdminCadastrosLocaisLocalIdRoute: typeof AdminCadastrosLocaisLocalIdRoute
}

const AdminCadastrosLocaisRouteChildren: AdminCadastrosLocaisRouteChildren = {
  AdminCadastrosLocaisLocalIdRoute: AdminCadastrosLocaisLocalIdRoute,
}

const AdminCadastrosLocaisRouteWithChildren =
  AdminCadastrosLocaisRoute._addFileChildren(AdminCadastrosLocaisRouteChildren)

interface AdminCadastrosProdutosRouteChildren {
  AdminCadastrosProdutosProdutoIdRoute: typeof AdminCadastrosProdutosProdutoIdRoute
}

const AdminCadastrosProdutosRouteChildren: AdminCadastrosProdutosRouteChildren =
  {
    AdminCadastrosProdutosProdutoIdRoute: AdminCadastrosProdutosProdutoIdRoute,
  }

const AdminCadastrosProdutosRouteWithChildren =
  AdminCadastrosProdutosRoute._addFileChildren(
    AdminCadastrosProdutosRouteChildren,
  )

interface AdminCadastrosProgramasRouteChildren {
  AdminCadastrosProgramasProgramaIdRoute: typeof AdminCadastrosProgramasProgramaIdRoute
}

const AdminCadastrosProgramasRouteChildren: AdminCadastrosProgramasRouteChildren =
  {
    AdminCadastrosProgramasProgramaIdRoute:
      AdminCadastrosProgramasProgramaIdRoute,
  }

const AdminCadastrosProgramasRouteWithChildren =
  AdminCadastrosProgramasRoute._addFileChildren(
    AdminCadastrosProgramasRouteChildren,
  )

interface AdminCadastrosUsuariosRouteChildren {
  AdminCadastrosUsuariosUsuarioIdRoute: typeof AdminCadastrosUsuariosUsuarioIdRoute
}

const AdminCadastrosUsuariosRouteChildren: AdminCadastrosUsuariosRouteChildren =
  {
    AdminCadastrosUsuariosUsuarioIdRoute: AdminCadastrosUsuariosUsuarioIdRoute,
  }

const AdminCadastrosUsuariosRouteWithChildren =
  AdminCadastrosUsuariosRoute._addFileChildren(
    AdminCadastrosUsuariosRouteChildren,
  )

interface AdminRouteChildren {
  AdminAssinadasRoute: typeof AdminAssinadasRouteWithChildren
  AdminBackupRoute: typeof AdminBackupRouteWithChildren
  AdminCompletarCadastroRoute: typeof AdminCompletarCadastroRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminControleAssinaturasRoute: typeof AdminControleAssinaturasRoute
  AdminControleEntradasRoute: typeof AdminControleEntradasRoute
  AdminConversasRoute: typeof AdminConversasRoute
  AdminMeusAssinadosRoute: typeof AdminMeusAssinadosRouteWithChildren
  AdminMinhasAssinaturasRoute: typeof AdminMinhasAssinaturasRouteWithChildren
  AdminMinhasRequisicoesRoute: typeof AdminMinhasRequisicoesRoute
  AdminRequisicaoRoute: typeof AdminRequisicaoRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRouteWithChildren
  AdminWhatsappUsuariosRoute: typeof AdminWhatsappUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCadastrosLocaisRoute: typeof AdminCadastrosLocaisRouteWithChildren
  AdminCadastrosProdutosRoute: typeof AdminCadastrosProdutosRouteWithChildren
  AdminCadastrosProgramasRoute: typeof AdminCadastrosProgramasRouteWithChildren
  AdminCadastrosUsuariosRoute: typeof AdminCadastrosUsuariosRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinadasRoute: AdminAssinadasRouteWithChildren,
  AdminBackupRoute: AdminBackupRouteWithChildren,
  AdminCompletarCadastroRoute: AdminCompletarCadastroRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminControleAssinaturasRoute: AdminControleAssinaturasRoute,
  AdminControleEntradasRoute: AdminControleEntradasRoute,
  AdminConversasRoute: AdminConversasRoute,
  AdminMeusAssinadosRoute: AdminMeusAssinadosRouteWithChildren,
  AdminMinhasAssinaturasRoute: AdminMinhasAssinaturasRouteWithChildren,
  AdminMinhasRequisicoesRoute: AdminMinhasRequisicoesRoute,
  AdminRequisicaoRoute: AdminRequisicaoRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRouteWithChildren,
  AdminWhatsappUsuariosRoute: AdminWhatsappUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCadastrosLocaisRoute: AdminCadastrosLocaisRouteWithChildren,
  AdminCadastrosProdutosRoute: AdminCadastrosProdutosRouteWithChildren,
  AdminCadastrosProgramasRoute: AdminCadastrosProgramasRouteWithChildren,
  AdminCadastrosUsuariosRoute: AdminCadastrosUsuariosRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
