/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminRequisicaoRouteImport } from './routes/admin.requisicao'
import { Route as AdminMinhasAssinaturasRouteImport } from './routes/admin.minhas-assinaturas'
import { Route as AdminMeusAssinadosRouteImport } from './routes/admin.meus-assinados'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCompletarCadastroRouteImport } from './routes/admin.completar-cadastro'
import { Route as AdminAssinadasRouteImport } from './routes/admin.assinadas'
import { Route as AdminCadastrosUsuariosRouteImport } from './routes/admin.cadastros.usuarios'
import { Route as AdminCadastrosProgramasRouteImport } from './routes/admin.cadastros.programas'
import { Route as AdminCadastrosProdutosRouteImport } from './routes/admin.cadastros.produtos'
import { Route as AdminCadastrosLocaisRouteImport } from './routes/admin.cadastros.locais'
import { Route as AdminSolicitacoesRequisicaoIdPdfRouteImport } from './routes/admin.solicitacoes.$requisicaoId.pdf'
import { Route as AdminMinhasAssinaturasRequisicaoIdPdfRouteImport } from './routes/admin.minhas-assinaturas.$requisicaoId.pdf'
import { Route as AdminMeusAssinadosRequisicaoIdPdfRouteImport } from './routes/admin.meus-assinados.$requisicaoId.pdf'
import { Route as AdminCadastrosUsuariosUsuarioIdRouteImport } from './routes/admin.cadastros.usuarios.$usuarioId'
import { Route as AdminCadastrosProdutosProdutoIdRouteImport } from './routes/admin.cadastros.produtos.$produtoId'
import { Route as AdminAssinadasRequisicaoIdPdfRouteImport } from './routes/admin.assinadas.$requisicaoId.pdf'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequisicaoRoute = AdminRequisicaoRouteImport.update({
  id: '/requisicao',
  path: '/requisicao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMinhasAssinaturasRoute = AdminMinhasAssinaturasRouteImport.update({
  id: '/minhas-assinaturas',
  path: '/minhas-assinaturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMeusAssinadosRoute = AdminMeusAssinadosRouteImport.update({
  id: '/meus-assinados',
  path: '/meus-assinados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompletarCadastroRoute = AdminCompletarCadastroRouteImport.update({
  id: '/completar-cadastro',
  path: '/completar-cadastro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssinadasRoute = AdminAssinadasRouteImport.update({
  id: '/assinadas',
  path: '/assinadas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosUsuariosRoute = AdminCadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosProgramasRoute = AdminCadastrosProgramasRouteImport.update({
  id: '/cadastros/programas',
  path: '/cadastros/programas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosProdutosRoute = AdminCadastrosProdutosRouteImport.update({
  id: '/cadastros/produtos',
  path: '/cadastros/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCadastrosLocaisRoute = AdminCadastrosLocaisRouteImport.update({
  id: '/cadastros/locais',
  path: '/cadastros/locais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRequisicaoIdPdfRoute =
  AdminSolicitacoesRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminSolicitacoesRoute,
  } as any)
const AdminMinhasAssinaturasRequisicaoIdPdfRoute =
  AdminMinhasAssinaturasRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminMinhasAssinaturasRoute,
  } as any)
const AdminMeusAssinadosRequisicaoIdPdfRoute =
  AdminMeusAssinadosRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminMeusAssinadosRoute,
  } as any)
const AdminCadastrosUsuariosUsuarioIdRoute =
  AdminCadastrosUsuariosUsuarioIdRouteImport.update({
    id: '/$usuarioId',
    path: '/$usuarioId',
    getParentRoute: () => AdminCadastrosUsuariosRoute,
  } as any)
const AdminCadastrosProdutosProdutoIdRoute =
  AdminCadastrosProdutosProdutoIdRouteImport.update({
    id: '/$produtoId',
    path: '/$produtoId',
    getParentRoute: () => AdminCadastrosProdutosRoute,
  } as any)
const AdminAssinadasRequisicaoIdPdfRoute =
  AdminAssinadasRequisicaoIdPdfRouteImport.update({
    id: '/$requisicaoId/pdf',
    path: '/$requisicaoId/pdf',
    getParentRoute: () => AdminAssinadasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRoute
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRoute
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRoute
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRoute
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/assinadas': typeof AdminAssinadasRouteWithChildren
  '/admin/completar-cadastro': typeof AdminCompletarCadastroRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/meus-assinados': typeof AdminMeusAssinadosRouteWithChildren
  '/admin/minhas-assinaturas': typeof AdminMinhasAssinaturasRouteWithChildren
  '/admin/requisicao': typeof AdminRequisicaoRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/cadastros/locais': typeof AdminCadastrosLocaisRoute
  '/admin/cadastros/produtos': typeof AdminCadastrosProdutosRouteWithChildren
  '/admin/cadastros/programas': typeof AdminCadastrosProgramasRoute
  '/admin/cadastros/usuarios': typeof AdminCadastrosUsuariosRouteWithChildren
  '/admin/assinadas/$requisicaoId/pdf': typeof AdminAssinadasRequisicaoIdPdfRoute
  '/admin/cadastros/produtos/$produtoId': typeof AdminCadastrosProdutosProdutoIdRoute
  '/admin/cadastros/usuarios/$usuarioId': typeof AdminCadastrosUsuariosUsuarioIdRoute
  '/admin/meus-assinados/$requisicaoId/pdf': typeof AdminMeusAssinadosRequisicaoIdPdfRoute
  '/admin/minhas-assinaturas/$requisicaoId/pdf': typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
  '/admin/solicitacoes/$requisicaoId/pdf': typeof AdminSolicitacoesRequisicaoIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/assinadas'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin/'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/assinadas'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/assinadas'
    | '/admin/completar-cadastro'
    | '/admin/configuracoes'
    | '/admin/meus-assinados'
    | '/admin/minhas-assinaturas'
    | '/admin/requisicao'
    | '/admin/solicitacoes'
    | '/admin/'
    | '/admin/cadastros/locais'
    | '/admin/cadastros/produtos'
    | '/admin/cadastros/programas'
    | '/admin/cadastros/usuarios'
    | '/admin/assinadas/$requisicaoId/pdf'
    | '/admin/cadastros/produtos/$produtoId'
    | '/admin/cadastros/usuarios/$usuarioId'
    | '/admin/meus-assinados/$requisicaoId/pdf'
    | '/admin/minhas-assinaturas/$requisicaoId/pdf'
    | '/admin/solicitacoes/$requisicaoId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requisicao': {
      id: '/admin/requisicao'
      path: '/requisicao'
      fullPath: '/admin/requisicao'
      preLoaderRoute: typeof AdminRequisicaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/minhas-assinaturas': {
      id: '/admin/minhas-assinaturas'
      path: '/minhas-assinaturas'
      fullPath: '/admin/minhas-assinaturas'
      preLoaderRoute: typeof AdminMinhasAssinaturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/meus-assinados': {
      id: '/admin/meus-assinados'
      path: '/meus-assinados'
      fullPath: '/admin/meus-assinados'
      preLoaderRoute: typeof AdminMeusAssinadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/completar-cadastro': {
      id: '/admin/completar-cadastro'
      path: '/completar-cadastro'
      fullPath: '/admin/completar-cadastro'
      preLoaderRoute: typeof AdminCompletarCadastroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assinadas': {
      id: '/admin/assinadas'
      path: '/assinadas'
      fullPath: '/admin/assinadas'
      preLoaderRoute: typeof AdminAssinadasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/usuarios': {
      id: '/admin/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/admin/cadastros/usuarios'
      preLoaderRoute: typeof AdminCadastrosUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/programas': {
      id: '/admin/cadastros/programas'
      path: '/cadastros/programas'
      fullPath: '/admin/cadastros/programas'
      preLoaderRoute: typeof AdminCadastrosProgramasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/produtos': {
      id: '/admin/cadastros/produtos'
      path: '/cadastros/produtos'
      fullPath: '/admin/cadastros/produtos'
      preLoaderRoute: typeof AdminCadastrosProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cadastros/locais': {
      id: '/admin/cadastros/locais'
      path: '/cadastros/locais'
      fullPath: '/admin/cadastros/locais'
      preLoaderRoute: typeof AdminCadastrosLocaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes/$requisicaoId/pdf': {
      id: '/admin/solicitacoes/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/solicitacoes/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminSolicitacoesRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminSolicitacoesRoute
    }
    '/admin/minhas-assinaturas/$requisicaoId/pdf': {
      id: '/admin/minhas-assinaturas/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/minhas-assinaturas/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminMinhasAssinaturasRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminMinhasAssinaturasRoute
    }
    '/admin/meus-assinados/$requisicaoId/pdf': {
      id: '/admin/meus-assinados/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/meus-assinados/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminMeusAssinadosRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminMeusAssinadosRoute
    }
    '/admin/cadastros/usuarios/$usuarioId': {
      id: '/admin/cadastros/usuarios/$usuarioId'
      path: '/$usuarioId'
      fullPath: '/admin/cadastros/usuarios/$usuarioId'
      preLoaderRoute: typeof AdminCadastrosUsuariosUsuarioIdRouteImport
      parentRoute: typeof AdminCadastrosUsuariosRoute
    }
    '/admin/cadastros/produtos/$produtoId': {
      id: '/admin/cadastros/produtos/$produtoId'
      path: '/$produtoId'
      fullPath: '/admin/cadastros/produtos/$produtoId'
      preLoaderRoute: typeof AdminCadastrosProdutosProdutoIdRouteImport
      parentRoute: typeof AdminCadastrosProdutosRoute
    }
    '/admin/assinadas/$requisicaoId/pdf': {
      id: '/admin/assinadas/$requisicaoId/pdf'
      path: '/$requisicaoId/pdf'
      fullPath: '/admin/assinadas/$requisicaoId/pdf'
      preLoaderRoute: typeof AdminAssinadasRequisicaoIdPdfRouteImport
      parentRoute: typeof AdminAssinadasRoute
    }
  }
}

interface AdminAssinadasRouteChildren {
  AdminAssinadasRequisicaoIdPdfRoute: typeof AdminAssinadasRequisicaoIdPdfRoute
}

const AdminAssinadasRouteChildren: AdminAssinadasRouteChildren = {
  AdminAssinadasRequisicaoIdPdfRoute: AdminAssinadasRequisicaoIdPdfRoute,
}

const AdminAssinadasRouteWithChildren = AdminAssinadasRoute._addFileChildren(
  AdminAssinadasRouteChildren,
)

interface AdminMeusAssinadosRouteChildren {
  AdminMeusAssinadosRequisicaoIdPdfRoute: typeof AdminMeusAssinadosRequisicaoIdPdfRoute
}

const AdminMeusAssinadosRouteChildren: AdminMeusAssinadosRouteChildren = {
  AdminMeusAssinadosRequisicaoIdPdfRoute:
    AdminMeusAssinadosRequisicaoIdPdfRoute,
}

const AdminMeusAssinadosRouteWithChildren =
  AdminMeusAssinadosRoute._addFileChildren(AdminMeusAssinadosRouteChildren)

interface AdminMinhasAssinaturasRouteChildren {
  AdminMinhasAssinaturasRequisicaoIdPdfRoute: typeof AdminMinhasAssinaturasRequisicaoIdPdfRoute
}

const AdminMinhasAssinaturasRouteChildren: AdminMinhasAssinaturasRouteChildren =
  {
    AdminMinhasAssinaturasRequisicaoIdPdfRoute:
      AdminMinhasAssinaturasRequisicaoIdPdfRoute,
  }

const AdminMinhasAssinaturasRouteWithChildren =
  AdminMinhasAssinaturasRoute._addFileChildren(
    AdminMinhasAssinaturasRouteChildren,
  )

interface AdminSolicitacoesRouteChildren {
  AdminSolicitacoesRequisicaoIdPdfRoute: typeof AdminSolicitacoesRequisicaoIdPdfRoute
}

const AdminSolicitacoesRouteChildren: AdminSolicitacoesRouteChildren = {
  AdminSolicitacoesRequisicaoIdPdfRoute: AdminSolicitacoesRequisicaoIdPdfRoute,
}

const AdminSolicitacoesRouteWithChildren =
  AdminSolicitacoesRoute._addFileChildren(AdminSolicitacoesRouteChildren)

interface AdminCadastrosProdutosRouteChildren {
  AdminCadastrosProdutosProdutoIdRoute: typeof AdminCadastrosProdutosProdutoIdRoute
}

const AdminCadastrosProdutosRouteChildren: AdminCadastrosProdutosRouteChildren =
  {
    AdminCadastrosProdutosProdutoIdRoute: AdminCadastrosProdutosProdutoIdRoute,
  }

const AdminCadastrosProdutosRouteWithChildren =
  AdminCadastrosProdutosRoute._addFileChildren(
    AdminCadastrosProdutosRouteChildren,
  )

interface AdminCadastrosUsuariosRouteChildren {
  AdminCadastrosUsuariosUsuarioIdRoute: typeof AdminCadastrosUsuariosUsuarioIdRoute
}

const AdminCadastrosUsuariosRouteChildren: AdminCadastrosUsuariosRouteChildren =
  {
    AdminCadastrosUsuariosUsuarioIdRoute: AdminCadastrosUsuariosUsuarioIdRoute,
  }

const AdminCadastrosUsuariosRouteWithChildren =
  AdminCadastrosUsuariosRoute._addFileChildren(
    AdminCadastrosUsuariosRouteChildren,
  )

interface AdminRouteChildren {
  AdminAssinadasRoute: typeof AdminAssinadasRouteWithChildren
  AdminCompletarCadastroRoute: typeof AdminCompletarCadastroRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminMeusAssinadosRoute: typeof AdminMeusAssinadosRouteWithChildren
  AdminMinhasAssinaturasRoute: typeof AdminMinhasAssinaturasRouteWithChildren
  AdminRequisicaoRoute: typeof AdminRequisicaoRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCadastrosLocaisRoute: typeof AdminCadastrosLocaisRoute
  AdminCadastrosProdutosRoute: typeof AdminCadastrosProdutosRouteWithChildren
  AdminCadastrosProgramasRoute: typeof AdminCadastrosProgramasRoute
  AdminCadastrosUsuariosRoute: typeof AdminCadastrosUsuariosRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssinadasRoute: AdminAssinadasRouteWithChildren,
  AdminCompletarCadastroRoute: AdminCompletarCadastroRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminMeusAssinadosRoute: AdminMeusAssinadosRouteWithChildren,
  AdminMinhasAssinaturasRoute: AdminMinhasAssinaturasRouteWithChildren,
  AdminRequisicaoRoute: AdminRequisicaoRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminCadastrosLocaisRoute: AdminCadastrosLocaisRoute,
  AdminCadastrosProdutosRoute: AdminCadastrosProdutosRouteWithChildren,
  AdminCadastrosProgramasRoute: AdminCadastrosProgramasRoute,
  AdminCadastrosUsuariosRoute: AdminCadastrosUsuariosRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
