WITH classified_items (name_key, subcategoria) AS (
  VALUES
    ('ACIDO MURIATICO 1 L', 'Limpeza'),
    ('ACUCAR COMUM', 'Alimentício'),
    ('AGUA SANITARIA 1 L', 'Limpeza'),
    ('ARROZ PARBOLIZADO', 'Alimentício'),
    ('BANANADA OU GOIABADA EM POTE 500 G', 'Alimentício'),
    ('BISCOITO DE LEITE 400 G', 'Alimentício'),
    ('BISCOITO DOCE TIPO MARIA 350 G', 'Alimentício'),
    ('BISCOITO POPULAR SALGADO TIPO MINI CRACKER 350 G', 'Alimentício'),
    ('BISCOITO SALGADO TIPO CREAM CRACKER 350 G', 'Alimentício'),
    ('CABO DE ALUMINIO', 'Limpeza'),
    ('CAFE EM PO', 'Alimentício'),
    ('CERA LIQUIDA INCOLOR 750 ML', 'Limpeza'),
    ('CEREAIS PARA ALIMENTACAO INFANTIL 180G', 'Alimentício'),
    ('COLORIFICO SEM SAL 100 G', 'Alimentício'),
    ('COPO DESCARTAVEL 150 ML PCT C 100', 'Alimentício'),
    ('COPO DESCARTAVEL 200 ML PCT C 100', 'Alimentício'),
    ('COPO DESCARTAVEL 50 ML PCT C 100', 'Alimentício'),
    ('CREME DE LEITE 200 G', 'Alimentício'),
    ('DESINFETANTE DE AMBIENTES LIQUIDO CONCENTRADO 120 ML', 'Limpeza'),
    ('DESINFETANTE HOSPITALAR CONCENTRADO 5 LITROS', 'Limpeza'),
    ('DESINFETANTE LIQUIDO 500 ML', 'Limpeza'),
    ('DESODORIZADOR DE AR 360 ML', 'Limpeza'),
    ('DETERGENTE CONCENTRADO ALCALINO 20 L', 'Limpeza'),
    ('DETERGENTE LIQUIDO 500 ML', 'Limpeza'),
    ('DETERGENTE NEUTRO SUPER CONCENTRADO 1 L', 'Limpeza'),
    ('ERVILHA', 'Alimentício'),
    ('ESPONJA DE ACO PACOTE COM 8 UNIDADES', 'Limpeza'),
    ('ESPONJA DUPLA FACE', 'Limpeza'),
    ('EXTRATO DE TOMATE 300 G', 'Alimentício'),
    ('FARINHA DE MANDIOCA BRANCA 1 KG', 'Alimentício'),
    ('FARINHA DE TRIGO COM FERMENTO 1 KG', 'Alimentício'),
    ('FARINHA DE TRIGO SEM FERMENTO 1 KG', 'Alimentício'),
    ('FARINHA LACTEA SACHE 600 G', 'Alimentício'),
    ('FECULA DE MANDIOCA GOMA 1 KG', 'Alimentício'),
    ('FEIJAO CARIOCA 1 KG', 'Alimentício'),
    ('FEIJAO DE CORDA 1 KG', 'Alimentício'),
    ('FEIJAO PRETO 1KG', 'Alimentício'),
    ('FLANELAS', 'Limpeza'),
    ('FLOCOS DE MILHO 500 G', 'Alimentício'),
    ('GUARDANAPO DE PAPEL PCT C 50 UNIDADES', 'Alimentício'),
    ('INSETICIDA AEROSSOL 300 ML', 'Limpeza'),
    ('ISQUEIRO', 'Alimentício'),
    ('LIMPADOR INSTANTANEO MULTIUSO 500 ML', 'Limpeza'),
    ('LUSTRA MOVEIS 200 ML', 'Limpeza'),
    ('LUVA NITRILICA TAMANHO 8', 'Limpeza'),
    ('MACARRAO TIPO ESPAGHETTI 400 G', 'Alimentício'),
    ('MAIONESE 200 G', 'Alimentício'),
    ('MARGARINA VEGETAL COM SAL 3 KG', 'Alimentício'),
    ('MARGARINA VEGETAL 500 G', 'Alimentício'),
    ('MARMITA ISOPOR C 100 UND MARMITA DE ISOPOR COM 100 UNIDADES COM TAMPA COM 750 MILILITROS', 'Alimentício'),
    ('MILHO VERDE 170G RAMAS DE MILHO DRENADO E 280 GRAMAS DE PESO LIQUIDO', 'Alimentício'),
    ('MOP UMIDO COM SUPORTE', 'Limpeza'),
    ('OLEO DE SOJA REFINADO 900 ML', 'Alimentício'),
    ('PA PARA LIXO DE ZINCO', 'Limpeza'),
    ('PALITO DE DENTE', 'Alimentício'),
    ('PANO DE CHAO', 'Limpeza'),
    ('PANO DE PRATO', 'Alimentício'),
    ('PAO FRANCES', 'Alimentício'),
    ('PAPEL HIGIENICO PACOTE COM 4 ROLOS', 'Limpeza'),
    ('PAPEL TOALHA PACOTE COM 2 UNIDADES', 'Limpeza'),
    ('PIMENTA DO REINO MOIDA 20 G', 'Alimentício'),
    ('POLIDOR LIQUIDO DE ALUMINIO 500 ML', 'Limpeza'),
    ('POLPA DE FRUTA SABOR ACEROLA 1KG', 'Alimentício'),
    ('POLPA DE FRUTA SABOR CAJA 1KG', 'Alimentício'),
    ('POLPA DE FRUTA SABOR MARACUJA 1KG', 'Alimentício'),
    ('PULVERIZADOR 500 ML', 'Limpeza'),
    ('RAPADURA', 'Alimentício'),
    ('REFIL PARA MOP UMIDO', 'Limpeza'),
    ('REFRESCO EM PO SABORES VARIADOS 18 G', 'Alimentício'),
    ('RODO 40 CM', 'Limpeza'),
    ('RODO 60 CM', 'Limpeza'),
    ('SABAO EM BARRA PACOTE COM 05 UNIDADES', 'Limpeza'),
    ('SABAO EM PO 400 G', 'Limpeza'),
    ('SABONETE LIQUIDO ANTISSEPTICO 5 LITROS', 'Limpeza'),
    ('SACO DE LIXO 100 LITROS', 'Limpeza'),
    ('SACO DE LIXO 30 LITROS', 'Limpeza'),
    ('SACO DE LIXO 50 LITROS', 'Limpeza'),
    ('SACO PLASTICO', 'Alimentício'),
    ('SAL REFINADO IODADO 1 KG', 'Alimentício'),
    ('TEMPERO COMPLETO LIQUIDO 500 ML', 'Alimentício'),
    ('TEMPERO COMPLETO 300G', 'Alimentício'),
    ('TEMPERO EM TABLETE GALINHA E CARNE', 'Alimentício'),
    ('VASSOURA DE PALHA', 'Limpeza'),
    ('VASSOURA DE PELO', 'Limpeza'),
    ('VASSOURA SANITARIA', 'Limpeza'),
    ('VASSOURAO DE PELO', 'Limpeza'),
    ('VINAGRE DE ALCOOL 500ML', 'Alimentício')
)
UPDATE public.itens AS i
SET subcategoria = c.subcategoria
FROM classified_items AS c
WHERE trim(
    regexp_replace(
      translate(
        upper(COALESCE(i.nome, '')),
        'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇ',
        'AAAAAEEEEIIIIOOOOOUUUUC'
      ),
      '[^A-Z0-9]+',
      ' ',
      'g'
    )
  ) = c.name_key
  AND i.categoria ILIKE '%limpeza%'
  AND COALESCE(i.subcategoria, '') IS DISTINCT FROM c.subcategoria;
