// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzoiqjsttggtrjlrhcjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6b2lxanN0dGdndHJqbHJoY2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5MTE3MDcsImV4cCI6MjA5MjQ4NzcwN30.UPZR_Bs_PqbKB0kAoUUo3Jntvt3Y1XqxTgSxiOLykmA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});